### ISSUE TITLE
Function / parameter documentation

### ISSUE THREAD

**Issue by jhb1980** [uubram/RTCR#13]
Hi!

I'm finally having a chance to dive into working with your tool! I couldn't seem to find some more insight into the different score thresholding parameters associated with the rtcr umi_group_ec function, i.e.. MIN_SCORE_FOR_MERGE and MIN_SCORE_FOR_OFFSET...? What are the default values, and how does changing them affect the filtering into keepers and discarded reads...?

A perhaps more general related question: if base qualities in a given run are sub-par and consequently affect the recovery of clones: which parameter(s) would best be relaxed a little in order to carry a few more into the final results?

Thank you!

**Comment by uubram** [comment]
Thank you for your questions and your interest in RTCR! Just now, I updated RTCR so that the defaults are shown (see latest version, 0.5.1) for `rtcr umi_group_ec -h` (and `rtcr Checkout -h`).

> I'm finally having a chance to dive into working with your tool! I couldn't seem to find some more insight into the different score thresholding parameters associated with the rtcr umi_group_ec function, i.e.. MIN_SCORE_FOR_MERGE and MIN_SCORE_FOR_OFFSET...? What are the default values, and how does changing them affect the filtering into keepers and discarded reads...?

Hopefully, my description of the umi_group_ec algorithm below makes the thresholds clear(er).

umi_group_ec groups sequence reads together that have the same unique molecular identifier (UMI) and merges(/collapses) the reads in each UMI group into one (or more) consensus sequence(s). The parameters of umi_group_ec affect whether reads in a UMI group (i.e. sharing the same UMI) are merged into a consensus sequence, or are separated into different (consensus) sequences. After processing all the reads, for each UMI group the most abundant consensus sequence is kept (or the one with the highest summed Phred score in case of ties in abundance), discarding the other (consensus) sequences. Below follows a description of the process of merging reads in UMI groups and how the parameters affect this.

For every read, umi_group_ec creates a group identified by the UMI of the read and adds the read to it. If the UMI group already exists, the read will be aligned to any (consensus) sequences found in the group. Alignment uses a window of length K (default: 30) from the middle of the shorter sequence, allowing this window to shift at most MAX_OFFSET (default: 4) bases in either direction from the same index in the longer sequence, to find the window offset with the highest overlap score. Note, a read is discarded if it is shorter than the window length, K. Overlap score equals the difference between the number of matching and mismatching bases inside of the window, not counting (mis)matches between bases that have 0 Phred score ('N' quality character in fastq file). If the highest overlap score found in all alignments is below MIN_SCORE_FOR_MERGE (default: 24), the read is added to the group as a separate (consensus) sequence. Otherwise, the read is merged with the (consensus) sequence that had the highest overlap score, using a non-zero offset if the overlap score of the best non-zero offset was at least MIN_SCORE_FOR_OFFSET (default: 20).

The strictness of the overlap score thresholds (MIN_SCORE_FOR_MERGE and MIN_SCORE_FOR_OFFSET) directly depends on the window length, K, because the overlap score cannot be higher than K (i.e. K matching bases) nor less than -K (i.e. K mismatching bases). Increasing the thresholds makes them more strict, potentially resulting in more discarded reads. Conversely, lowering the thresholds may result in fewer discarded reads. Note, all discarded reads and discarded consensus sequences are written to a separate fastq file.
 
> A perhaps more general related question: if base qualities in a given run are sub-par and consequently affect the recovery of clones: which parameter(s) would best be relaxed a little in order to carry a few more into the final results?

RTCR automatically adjusts its error correction parameters based on the quality of the data. It is not necessary to adjust parameters to 'carry a few more clones into the final results', because RTCR does not discard clones during error correction (as performed by `rtcr run`). That said, after error correction, clones are separated into 'ok' clones that end up in "results.tsv" and not-ok clones that end up in "discarded_clones.tsv". A clone is considered ok if its CDR3 is in-frame, does not have a stop-codon, and the minimum Phred quality score is at least 5. Although I do not recommend it, at the risk of increasing the number of false positives, you could consider lowering this minimum Phred threshold using `rtcr Config Defaults.min_phred_threshold`.

**Comment by jhb1980** [comment]
Quickly reopening with a question that would fit the topic:

What is the minimum number of reads required for error correction in a UMI group? And conversely, what is the fate of "singletons" in terms of reporting?

**Comment by uubram** [comment]
Error correction happens when reads are merged(/collapsed) into consensus sequences. Consensus is reached by selecting for every position in the sequence the most common base, and in case of ties of abundance, the base with highest Phred score. UMI groups consisting of a single read (which is what I think you mean by "singletons") will be reported as is (i.e. they won't be discarded).
