### ISSUE TITLE
my results.tsv is not loaded by immunarch::repLoad

### ISSUE THREAD

**Issue by nukaemon** [uubram/RTCR#24]
Hello @uubram

I tried to load my results.tsv to [immunarch](https://immunarch.com/index.html) package using repLoad function.
It automatically recognized the file format as 'airr' but it failed with an error saying "Column `cdr1` doesn't exist."
It is true that my results.tsv doesn't have 'cdr1' column, but am I supposed to have it?
Do you think AIRR format version should be 1.4 instead of 1.3 to be loaded into immunarch?

```
> dat <- repLoad("results.tsv")

== Step 1/3: loading repertoire files... ==

Processing "<initial>" ...
  -- [1/1] Parsing "results.tsv" -- airr
Error in `select()`:
! Can't subset columns that don't exist.
✖ Column `cdr1` doesn't exist.
Run `rlang::last_trace()` to see where the error occurred.



> rlang::last_trace()
<error/vctrs_error_subscript_oob>
Error in `select()`:
! Can't subset columns that don't exist.
✖ Column `cdr1` doesn't exist.
---
Backtrace:
    ▆
 1. ├─immunarch::repLoad("results.tsv")
 2. │ └─immunarch (local) .process_batch(batches[[batch_i]], .mode, .coding)
 3. │   └─immunarch (local) .read_repertoire(.filepath, .mode, .coding, ...)
 4. │     └─immunarch (local) parse_fun(.path, .mode, ...)
 5. │       └─df %<>% ...
 6. ├─dplyr::select_(...)
 7. └─dplyr:::select_.data.frame(...)
 8.   ├─dplyr::select(.data, !!!dots)
 9.   └─dplyr:::select.data.frame(.data, !!!dots)
Run rlang::last_trace(drop = FALSE) to see 18 hidden frames.
```

**Comment by uubram** [comment]
Dear @nukaemon,

The immunarch error is unlikely an issue of AIRR versions, because in both version 1.3 (the one RTCR uses) and in the [latest AIRR Rearrangement Schema](https://docs.airr-community.org/en/latest/datarep/rearrangements.html) (version 1.4.1 at the time of this writing) the 'cdr1' column is optional. This means immunarch should not throw an error if the 'cdr1' column is not included in the tsv file.

In case you are interested in testing if the results.tsv that RTCR produced complies to AIRR the standard, you can run the following lines in R:
```
library(airr)
validate_rearrangement(read_rearrangement("path/to/results.tsv"))
```
If the above code outputs 'TRUE' then the file complies. Today, using airr package version 1.4.1 I tested a results.tsv produced by the latest RTCR version (0.5.1), and it complied.

I think it could be useful if you report the immunarch error to the immunarch developers. Meanwhile, if you want to load your results.tsv into immunarch, the code below worked for me (using different paths of course):
```
library(airr)
library(immunarch)
x <- read_rearrangement("path/to/results.tsv")
x[, c("cdr1", "cdr2", "cdr1_aa", "cdr2_aa", "fwr1", "fwr2", "fwr3", "fwr4",
      "fwr1_aa", "fwr2_aa", "fwr3_aa", "fwr4_aa")] <- NA
write_rearrangement(data = x, file = "path/to/results_for_immunarch.tsv")
repLoad("path/to/results_for_immunarch.tsv")
```

Please let me know if you have any questions and if this resolves your issue.

Best wishes,
Bram

**Comment by nukaemon** [comment]
Hello @uubram

Thank you for your kind reply.
**validate_rearrangement** returns TRUE, so my results.tsv should be valid.

```
> library(airr)
> validate_rearrangement(read_rearrangement("results.tsv"))
[1] TRUE
```

I'm going to report the error caused by optional columns to immunarch developers.
I also appreciate for your suggestion to work around this.

Best regards,
