### ISSUE TITLE
ValueError: Quality score of 'N' should be 0

### ISSUE THREAD

**Issue by aqzas** [uubram/RTCR#3]
Hi
I meet this problem with all my fastq files even if I had deleted all reads contain 'N' from the file.
I'm new to this filed, so what could be the cause ?

**Comment by uubram** [comment]
Maybe there was an alignments.sam.gz from a previous run of RTCR. The pipeline will use that file instead of the provided fastq file if it already exists in the directory RTCR will write its results to.

See attached zip file for a script (n2zero.py) that can be used to set the quality scores of ambiguous bases ('N') to 0, so that you don't have to delete any reads. The script can be used to preprocess your data as follows (assuming the reads are in a file called "reads.fq"):

./n2zero.py -i reads.fq -o reads_fixed.fq -p 33

Because the script does not detect the Phred encoding, the "-p" option is required to set the encoding (either 33, or 64). After running the script, it should be possible to use RTCR with the "reads_fixed.fq" file.


[n2zero.py.zip](https://github.com/uubram/RTCR/files/1641821/n2zero.py.zip)

**Comment by aqzas** [comment]
Thank for the reply, it works
