### ISSUE TITLE
How-to: non-UMI paired-end RNA-seq data

### ISSUE THREAD

**Issue by jhb1980** [uubram/RTCR#9]
Hi - very nice and intuitive tool, thanks!
I may have missed this somewhere in the docs, apologies if so. Do I see it right that only a single fastq file can be used as input into 'rtcr run'? What would be the recommended approach for using RTCR with 'standard' paired-end whole-transcriptome RNA-seq? (A merge would leave many unassembled reads).

**Comment by uubram** [comment]
Thank you!
You are correct, the paired-end reads should be assembled before using 'rtcr run'. If you have many reads that fail, I'd suggest combining the assembled reads and those that failed to assemble into a single fastq file for 'rtcr run'. Although it is technically possible for RTCR to report a TCR for both the forward and reverse read of a failed read pair, I think it is unlikely for this to happen because in such a case the read pair should have been assembled successfully.

**Comment by jhb1980** [comment]
Thank you!
